include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: ignore
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore
    non_constant_identifier_names: ignore
    use_build_context_synchronously: ignore
    invalid_annotation_target: ignore
    todo: ignore
