name: tarea
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  auto_route: ^3.2.4
  google_fonts: ^2.3.1
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

  lint: ^1.8.2
  freezed: ^1.1.1

  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
