name: carrera_cucei_2022
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  auto_route: ^3.2.4
  google_fonts: ^2.3.1
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  dio: ^4.0.4
  material_design_icons_flutter: ^5.0.6595
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  dartz: ^0.10.1
  lottie: ^1.2.2
  intl: ^0.17.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  cool_alert: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter

  lint: ^1.8.2
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
