name: carrera_cucei_2022
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  auto_route: ^4.0.1
  google_fonts: ^2.3.2
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  dio: ^4.0.6
  material_design_icons_flutter: ^5.0.6595
  json_annotation: ^4.5.0
  shared_preferences: ^2.0.15
  dartz: ^0.10.1
  lottie: ^1.3.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  cool_alert: ^1.1.0
  google_maps_flutter: ^2.1.5
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter

  lint: ^1.8.2
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/map/
